# This file was generated by GoReleaser. DO NOT EDIT.
cask "backlot" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4d792494448449669c698c2e6dbe0e51432efa668a5ffd6843df59c552bb2aa6"
      url "https://github.com/massivemoose/backlot/releases/download/v#{version}/backlot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db094c87f553cc64fc13e69fd443ff10f4a1dbc4dbc2c24f90442bde4dedc41c"
      url "https://github.com/massivemoose/backlot/releases/download/v#{version}/backlot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6633c600ccf4e94818fc02fac0b5ab990cf69e04555721b520e5009e6d024b8"
      url "https://github.com/massivemoose/backlot/releases/download/v#{version}/backlot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "23d6e34ef623088f9785a436d2c4104318b7dd5ec398c813ffb30933207bdc6f"
      url "https://github.com/massivemoose/backlot/releases/download/v#{version}/backlot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "backlot"
  desc "Private workspace for public repos."
  homepage "https://github.com/massivemoose/backlot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backlot"

  # No zap stanza required

end
