# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backlot < Formula
  desc "Private workspace for public repos."
  homepage "https://github.com/massivemoose/backlot"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/massivemoose/backlot/releases/download/v0.2.0/backlot_0.2.0_darwin_amd64.tar.gz"
      sha256 "2e646fcaad6120edede7ffe34d2382dfd19b678263935f1775a8ba8fbedcf06d"

      define_method(:install) do
        bin.install "backlot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/massivemoose/backlot/releases/download/v0.2.0/backlot_0.2.0_darwin_arm64.tar.gz"
      sha256 "0b2d4dda6b0ba4bd4ba702c3caeec4e901316afebd2936689b63ae41ea50db9c"

      define_method(:install) do
        bin.install "backlot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/massivemoose/backlot/releases/download/v0.2.0/backlot_0.2.0_linux_amd64.tar.gz"
      sha256 "482e82f402f877b7dd3c0da06d805fec4f94923f8fbd8fc65597e6f6e530f7b5"
      define_method(:install) do
        bin.install "backlot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/massivemoose/backlot/releases/download/v0.2.0/backlot_0.2.0_linux_arm64.tar.gz"
      sha256 "2e93a4e258d0c08fcba5488c1306fc28e03373cf7a53dfc63bae50b5efa1c92b"
      define_method(:install) do
        bin.install "backlot"
      end
    end
  end
end
